---
- src: https://github.com/open-io/ansible-role-openio-gridinit.git
  version: master
  name: gridinit

- src: https://github.com/open-io/ansible-role-openio-repository.git
  version: master
  name: repo

- src: https://github.com/open-io/ansible-role-openio-elasticsearch.git
  version: master
  name: elasticsearch
...
