# roles/logstash/tasks/main.yml
---
- name: "Include {{ ansible_distribution }} variables"
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"
  tags: install

- name: Create the 'openio' group
  group:
    name: openio
    gid: "{{ openio_group_openio_gid | default('220')}}"
  tags: install

- name: Create the 'openio' user
  user:
    name: openio
    comment: "openio account"
    uid: "{{ openio_user_openio_uid | default('120')}}"
    group: openio
  tags: install

- name: "Include {{ ansible_distribution }} tasks"
  include_tasks: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"
  tags: install

- name: Test directories presence
  stat:
    path: "{{ item }}"
  register: _dir
  with_items:
    - "/etc/gridinit.d/{{ openio_logstash_namespace }}"
    - "{{ openio_logstash_sysconfig_dir }}/logstash-{{ openio_logstash_serviceid }}"
    - "{{ openio_logstash_volume }}"
    - "{{ openio_logstash_sysconfig_dir }}/{{ openio_logstash_servicename }}/conf.d"
    - "{{ openio_logstash_pid_directory }}"

- name: Ensure directories exists
  file:
    path: "{{ item.item }}"
    state: directory
    owner: openio
    group: openio
    mode: 0755
    recurse: true
  with_items: "{{ _dir.results }}"
  when: not item.stat.exists
  tags: install

- name: Ensure log directory
  file:
    path: "/var/log/oio/sds/{{ openio_logstash_namespace }}/logstash-{{ openio_logstash_serviceid }}"
    state: directory
    owner: "{{ syslog_user }}"
    group: openio
    mode: 0770
    recurse: true
  tags: install

- name: Ensure logstash pid directory is persistant
  lineinfile:
    dest: /etc/tmpfiles.d/logstash.conf
    create: true
    line: "d {{ openio_logstash_pid_directory }} 755 openio openio -"
    owner: openio
    group: openio
    mode: 0644
  tags: install
  when: openio_logstash_pid_directory.split(' ')[0] | dirname is match("/run/.*")

- name: Generate configuration files
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: openio
    group: openio
    mode: 0644
  with_items:
    - src: "log4j2.properties.j2"
      dest: "{{ openio_logstash_sysconfig_dir }}/\
        {{ openio_logstash_servicename }}/log4j2.properties"
    - src: "01-beats-input.conf.j2"
      dest: "{{ openio_logstash_sysconfig_dir }}/\
        {{ openio_logstash_servicename }}/conf.d/01-beats-input.conf"
    - src: "10-filter.conf.j2"
      dest: "{{ openio_logstash_sysconfig_dir }}/\
        {{ openio_logstash_servicename }}/conf.d/10-filter.conf"
    - src: "30-elasticsearch-output.conf.j2"
      dest: "{{ openio_logstash_sysconfig_dir }}/\
        {{ openio_logstash_servicename }}/conf.d/30-elasticsearch-output.conf"
    - src: "logstash.yml.j2"
      dest: "{{ openio_logstash_sysconfig_dir }}/\
        {{ openio_logstash_servicename }}/logstash.yml"
    - src: "pipelines.yml.j2"
      dest: "{{ openio_logstash_sysconfig_dir }}/\
        {{ openio_logstash_servicename }}/pipelines.yml"
    - src: "gridinit_logstash.conf.j2"
      dest: "{{ openio_logstash_gridinit_dir }}/{{ openio_logstash_gridinit_file_prefix }}\
        {{ openio_logstash_servicename }}.conf"
  register: _logstash_conf

- name: Copy openio template
  copy:
    src: conf/
    dest: "{{ openio_logstash_sysconfig_dir }}/{{ openio_logstash_servicename }}/conf.d"
    owner: openio
    group: openio

- name: restart logstash
  shell: |
    gridinit_cmd reload
    gridinit_cmd restart  {{openio_logstash_namespace}}-logstash-{{openio_logstash_serviceid}}
  when:
    - _logstash_conf.changed
    - not openio_logstash_provision_only
  tags: configure
...
